CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE SCHEMA IF NOT EXISTS diagnose_virtual;

CREATE EXTENSION postgis;

CREATE TABLE diagnose_virtual.usuario (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    cpf character varying(11) NOT NULL,
    email character varying(50) NOT NULL,
    password_hash bytea NOT NULL,
    password_salt bytea NOT NULL,
    ativo boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_usuario" PRIMARY KEY (id)
);

CREATE TABLE diagnose_virtual.fazenda (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NULL,
    demarcacao_geom geometry NULL,
    concluida boolean NOT NULL DEFAULT FALSE,
    ativa boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_fazenda" PRIMARY KEY (id),
    CONSTRAINT "FK_fazenda_usuario_id_usuario" FOREIGN KEY (id_usuario) REFERENCES diagnose_virtual.usuario (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.dados_fazenda (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cultura character varying(100) NOT NULL,
    area_total double precision NOT NULL,
    quantidade_lavouras integer NOT NULL,
    id_fazenda integer NULL,
    CONSTRAINT "PK_dados_fazenda" PRIMARY KEY (id),
    CONSTRAINT "FK_dados_fazenda_fazenda_id_fazenda" FOREIGN KEY (id_fazenda) REFERENCES diagnose_virtual.fazenda (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.lavoura (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_fazenda integer NULL,
    demarcacao_geom geometry NOT NULL,
    concluida boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_lavoura" PRIMARY KEY (id),
    CONSTRAINT "FK_lavoura_fazenda_id_fazenda" FOREIGN KEY (id_fazenda) REFERENCES diagnose_virtual.fazenda (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.localizacao_fazenda (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(30) NOT NULL,
    estado character varying(20) NOT NULL,
    municipio character varying(50) NOT NULL,
    proprietario character varying(50) NOT NULL,
    gerente character varying(30) NOT NULL,
    contato character varying(50) NOT NULL,
    ponto_referencia character varying(70) NOT NULL,
    id_fazenda integer NULL,
    CONSTRAINT "PK_localizacao_fazenda" PRIMARY KEY (id),
    CONSTRAINT "FK_localizacao_fazenda_fazenda_id_fazenda" FOREIGN KEY (id_fazenda) REFERENCES diagnose_virtual.fazenda (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.dados_lavoura (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(20) NOT NULL,
    mes_ano_plantio character varying(7) NOT NULL,
    cultivar character varying(30) NOT NULL,
    numero_plantas integer NOT NULL,
    expacamento_vertical double precision NOT NULL,
    espacamento_horizontal double precision NOT NULL,
    observacoes character varying(250) NOT NULL,
    id_lavoura integer NULL,
    CONSTRAINT "PK_dados_lavoura" PRIMARY KEY (id),
    CONSTRAINT "FK_dados_lavoura_lavoura_id_lavoura" FOREIGN KEY (id_lavoura) REFERENCES diagnose_virtual.lavoura (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.talhao (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    geometria_geom geometry NOT NULL,
    id_lavoura integer NULL,
    CONSTRAINT "PK_talhao" PRIMARY KEY (id),
    CONSTRAINT "FK_talhao_lavoura_id_lavoura" FOREIGN KEY (id_lavoura) REFERENCES diagnose_virtual.lavoura (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_dados_fazenda_id" ON diagnose_virtual.dados_fazenda (id);

CREATE UNIQUE INDEX "IX_dados_fazenda_id_fazenda" ON diagnose_virtual.dados_fazenda (id_fazenda);

CREATE UNIQUE INDEX "IX_dados_lavoura_id" ON diagnose_virtual.dados_lavoura (id);

CREATE UNIQUE INDEX "IX_dados_lavoura_id_lavoura" ON diagnose_virtual.dados_lavoura (id_lavoura);

CREATE UNIQUE INDEX "IX_fazenda_id" ON diagnose_virtual.fazenda (id);

CREATE INDEX "IX_fazenda_id_usuario" ON diagnose_virtual.fazenda (id_usuario);

CREATE UNIQUE INDEX "IX_lavoura_id" ON diagnose_virtual.lavoura (id);

CREATE INDEX "IX_lavoura_id_fazenda" ON diagnose_virtual.lavoura (id_fazenda);

CREATE UNIQUE INDEX "IX_localizacao_fazenda_id" ON diagnose_virtual.localizacao_fazenda (id);

CREATE UNIQUE INDEX "IX_localizacao_fazenda_id_fazenda" ON diagnose_virtual.localizacao_fazenda (id_fazenda);

CREATE UNIQUE INDEX "IX_talhao_id" ON diagnose_virtual.talhao (id);

CREATE INDEX "IX_talhao_id_lavoura" ON diagnose_virtual.talhao (id_lavoura);

CREATE UNIQUE INDEX "IX_usuario_cpf" ON diagnose_virtual.usuario (cpf);

CREATE UNIQUE INDEX "IX_usuario_email" ON diagnose_virtual.usuario (email);

CREATE UNIQUE INDEX "IX_usuario_id" ON diagnose_virtual.usuario (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200128012919_1', '3.1.1');

