CREATE TABLE diagnose_virtual.monitoramento (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_fazenda integer NULL,
    data_monitoramento timestamp without time zone NOT NULL,
    CONSTRAINT "PK_monitoramento" PRIMARY KEY (id),
    CONSTRAINT "FK_monitoramento_fazenda_id_fazenda" FOREIGN KEY (id_fazenda) REFERENCES diagnose_virtual.fazenda (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.problema_monitoramento (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_monitoramento integer NULL,
    ponto_geom geometry NOT NULL,
    descricao character varying(140) NOT NULL,
    recomendacao character varying(140) NOT NULL,
    CONSTRAINT "PK_problema_monitoramento" PRIMARY KEY (id),
    CONSTRAINT "FK_problema_monitoramento_monitoramento_id_monitoramento" FOREIGN KEY (id_monitoramento) REFERENCES diagnose_virtual.monitoramento (id) ON DELETE RESTRICT
);

CREATE TABLE diagnose_virtual.upload_monitoramento (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_monitoramento integer NULL,
    nome_arquivo character varying(25) NOT NULL,
    url character varying(100) NOT NULL,
    CONSTRAINT "PK_upload_monitoramento" PRIMARY KEY (id),
    CONSTRAINT "FK_upload_monitoramento_monitoramento_id_monitoramento" FOREIGN KEY (id_monitoramento) REFERENCES diagnose_virtual.monitoramento (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_monitoramento_id" ON diagnose_virtual.monitoramento (id);

CREATE INDEX "IX_monitoramento_id_fazenda" ON diagnose_virtual.monitoramento (id_fazenda);

CREATE UNIQUE INDEX "IX_problema_monitoramento_id" ON diagnose_virtual.problema_monitoramento (id);

CREATE INDEX "IX_problema_monitoramento_id_monitoramento" ON diagnose_virtual.problema_monitoramento (id_monitoramento);

CREATE UNIQUE INDEX "IX_upload_monitoramento_id" ON diagnose_virtual.upload_monitoramento (id);

CREATE INDEX "IX_upload_monitoramento_id_monitoramento" ON diagnose_virtual.upload_monitoramento (id_monitoramento);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200205024945_4', '3.1.1');

